### ISSUE TITLE
Unable to read Yubikey NEO

### ISSUE THREAD

**Issue by gee-one** [CyanogenMod/android_device_lge_bullhead#3]
Using cm-13.0-20160118-NIGHTLY-bullhead.zip, I am unable tor read Yubikey NEO via NFC.  I confirmed that this works with the stock MMB29P rom.

>01-18 15:45:38.504: E/BrcmNfcJni(2996): nfaConnectionCallback: NFA_SELECT_RESULT_EVT error: status = 3
>01-18 15:45:38.506: E/BrcmNfcNfa(2996): There's pending NFC_DiscoveryStart

I am able to read other NFC tags without issues in both CM and stock ROM.

I believe this is a similar issue as the angler:
https://github.com/CyanogenMod/android_device_huawei_angler/issues/1

**Comment by wk** [comment]
@cyanogen 
@gee-one 
@jakew02 

There shouldn't be any reason to import pre-built binary libnfc-nci to resolve this issue.

Builds MMB29K (bullhead) and MMB29M (angler) are based on on upstream libnfc-nci tagged android-6.0.1_r1 and android-6.0.1_r3 respectively. CyanogenMod/android_external_libnfc-nci currently tracks android-6.0.1_r3. 

The newer build MMB29P (bullhead, angler) relies on upstream tagged android-6.0.1_r8; it's likely that the regression was introduced by a mismatch between newer vendor firmware in that build and older libnfc-nci, breaking the ability to interact with certain NFC devices, including the Yubikey NEO.

This problem has been observed on both bullhead and angler devices:
CyanogenMod/android_device_huawei_angler#1
CyanogenMod/android_device_lge_bullhead#3

There is a pull request at jakew02/proprietary_vendor_lge#1 which solves the problem by pulling the pre-built, more recent libnci libraries from the vendor, but this is messy and indirect.

The problem should probably instead be resolved by bumping CyanogenMod/android_external_libnfc-nci to 6.0.3_r8 so that the correct version for the most recent vendor firmware is built in the next nightly build.

**Comment by jakew02** [comment]
there are no differences between r3 and r10 for external/libnfc-nci at a quick glance

**Comment by wk** [comment]
@jakew02 

Just noticed that none of the recent commits since 6.0.1_r3 was tagged made it into 6.0.3_r8 and the delta between the two is nil. 

This presents an additional problem, since the solution @gee-one proposed in jakew02/proprietary_vendor_lge#1 *does* in fact work, i.e., the vendor built libnfc-nci from MMB29P functions correctly, whereas the current CyanogenMod daily build does not. Perhaps something more subtle is at play (vendor silently backporting, build environment, ...)

**Comment by gee-one** [comment]
Forgot to close this.  This was fixed upstream.
